# Generated by Django 3.2.4 on 2021-06-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0002_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='view_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
